# Setup
title:        Aether Interactive
tagline:      Interactives && video games for gynoids || friends
baseurl:      ""
paginate:     1
locale:       "en" 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown